name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - "opened"
    branches:
      - dev
jobs:
  # Lint:
  #   runs-on: ubuntu-latest
  #   container: node:14
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Before Script
  #       run: yarn install --frozen-lockfile
  #     - name: Run Lint
  #       run: yarn run lint
  Test:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}

    env:
      TESTE: ${{ secrets.TESTE }}
    steps:
      - run: echo Valor ${{ github.base_ref }}
