name: GitHub Actions Demo
run-name: ${{ github.base_ref }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # Lint:
  #   runs-on: ubuntu-latest
  #   container: node:14
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Before Script
  #       run: yarn install --frozen-lockfile
  #     - name: Run Lint
  #       run: yarn run lint
  Test:
    runs-on: ubuntu-latest
    environment: $GITHUB_BASE_REF

    env:
      TESTE: ${{ secrets.TESTE }}
    steps:
      - run: echo Valor $TESTE
